name: CI

on:
  push:
    branches:
      - main  # Adjust based on your branch naming convention
  pull_request:
    branches:
      - main  # Adjust based on your branch naming convention

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have any dependencies
        
    - name: Run tests
      run: |
        python -m pytest  # Assuming you're using pytest for testing

    - name: Generate artifact
      run: |
        mkdir -p artifacts
        mv output.txt artifacts/
      if: ${{ github.event_name == 'pull_request' || always() }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifacts/
      if: ${{ github.event_name == 'pull_request' }}
